baseurl = "http://yourSiteHere"
languageCode = "en-us"
title = "KaweKamo"
copyright="lorratz"
publishDir="www"

[params]
    description="3481 Melrose Place | Beverly Hills, CA 90210 | 123.456.7890"
    brand="Lorratz"
    author="lorratz ltd"
    background="/img/intro-pic.jpg"
    [[params.slides]]
        path="/img/slide-1.jpg"
    [[params.slides]]
        path="/img/slide-2.jpg"
    [[params.slides]]
        path="/img/slide-3.jpg"

[[pages]]
title="home"
slug="slug"
content="content"
draft=false
[[pages.sections]]
 name="section-1"
 title="Build a Website worthy visiting"
 body="OMG"

[[pages]]
title="about"
slug="slug"
content="content"
draft=false
[[pages.sections]]
  name = "About Us"
[[pages.sections]]
  name = "team"
  title="Our Team"
 [[pages.sections.subsections]]
  name="john Smith"
  body="Job title"
 [[pages.sections.subsections]]
  name="john Smith"
  body="Job title"
 [[pages.sections.subsections]]
  name="john Smith"
  body="Job title"

[[pages]]
title="blog"
slug="slug"
content="content"
draft=false
[[pages.sections]]
  photo="/img/slide-1.jpg"
  name = "About Us"
  title="Post Title 1"
  body = "## hey yourSiteHere"
[[pages.sections]]
  photo="/img/slide-2.jpg"
  name = "About Us"
  title="POST Title 2"
  body = "## hey yourSiteHere"
[[pages.sections]]
  photo="/img/slide-3.jpg"
  title="POST Title 3"
  name = "About Us"
  body = "## hey yourSiteHere"

[[pages]]
title="contact"
slug="slug"
content="contact"
draft=false
[[pages.sections]]
phone="123.456.7890"
email="name@example.com"
address="P.O Box 1190 mwanza Tanzania"
