baseurl = "http://yourSiteHere"
languageCode = "en-us"
title = "my new lora site"
publishDir="www"

[[pages]]
title="home"
slug="slug"
content="content"
draft=false
[[pages.sections]]
 name="section-1"
 body="OMG"

[[pages]]
title="about"
slug="slug"
content="content"
draft=false
[[pages.sections]]
 name="section a"
 body="## hey yourSiteHere"

[[pages.sections]]
 name="section b"
 body="## hey yourSiteHere"

[[pages]]
title="products"
slug="slug"
content="content"
draft=false

[[pages]]
title="contact"
slug="slug"
content="contact"
draft=false
